baseURL = 'https://cristianezabot.com.br/'
languageCode = 'pt-br'
title = 'Cristiane Zabot - Psicoterapeuta'

[params]
  seotitle = 'Cristiane Zabot — Psicoterapeuta de Mulheres em Joinville e Online'


